# Generated by Django 4.0.6 on 2022-07-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='born_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='born at'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
