# Generated by Django 4.0.6 on 2022-07-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_grade_grade_four'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
