# Generated by Django 4.0.6 on 2022-07-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='born_at',
            field=models.DateField(blank=True, null=True, verbose_name='born at'),
        ),
    ]
