# Generated by Django 4.0.6 on 2022-07-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_student_born_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='sum',
            field=models.FloatField(default=0.0),
        ),
    ]
